# Generated by Django 4.2.3 on 2023-11-26 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_news_shop_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='shop_sizes',
        ),
    ]
