# Generated by Django 4.2.3 on 2023-11-26 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_remove_news_shop_sizes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Тема')),
                ('task', models.TextField(verbose_name='Описание задания')),
                ('answer', models.IntegerField(verbose_name='Ответ')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('level', models.FloatField(verbose_name='Уровень сложности')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
            },
        ),
    ]
